name: Nightly

on:
  workflow_dispatch:
  schedule:
  - cron: '53 7 * * *'

permissions:
  contents: read

jobs:
  linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install ghc
      run: |
        ghcup install ghc --set 9.10
        ghcup install cabal --set 3.14

    - name: Install dependencies
      run: |
        ghc --version
        cabal --version
        cabal update
        cabal build --dependencies-only -fembed_data_files -fnightly pandoc-cli
    - name: Build and install artifact
      run: |
        export ARTIFACTS=nightly-linux/pandoc-nightly-linux-$(date +%Y-%m-%d)
        mkdir -p ${ARTIFACTS}
        cabal install --installdir="${ARTIFACTS}" --install-method=copy -fembed_data_files -fnightly pandoc-cli
        strip "${ARTIFACTS}/pandoc"
        cp COPYRIGHT ${ARTIFACTS}/
        echo "Built from ${GITHUB_SHA}" > ${ARTIFACTS}/README.nightly.txt
    - uses: actions/upload-artifact@v7
      with:
        name: nightly-linux
        path: nightly-linux

